export CLIENT_ID="kubeflow-oidc-authservice"
export OIDC_PROVIDER=""
export AUTH_URL="http://188.166.138.216/dex/auth"
export TOKEN_URL="http://188.166.138.216/dex/token"
export OIDC_SCOPES="openid profile email groups"
export REDIRECT_URL="http://localhost:8000/seldon-deploy/auth/callback"
export RESOURCE_URI="https://graph.windows.net"
export CLIENT_SECRET=""